import { DEFAULT_HEADER_HEIGHT } from '../constants';
import type {
  MinorUnits,
  RegisterDensity,
  RegisterFilter,
  RegisterFilterField,
  RegisterGroupBy,
  RegisterGroupSummary,
  RegisterRowData,
  RegisterSelectionMode,
  RegisterVirtualRow,
  RowRange,
} from '../types';
import { buildFilteredRegisterRowModel } from '../utils/buildFilteredRegisterRowModel';
import { buildRegisterRowModel } from '../utils/buildRegisterRowModel';
import { computeRegisterFilterMatches } from '../utils/computeRegisterFilterMatches';
import { escapeHtml } from '../utils/escapeHtml';
import { formatMinorUnits } from '../utils/formatMinorUnits';
import { renderAccountPathHTML } from '../utils/renderAccountPathHTML';
import { renderFilterHighlightHTML } from '../utils/renderFilterHighlightHTML';
import { renderFlagDotHTML } from './EntryRenderer';

export interface RegisterRenderOptions {
  /** Canonical colon-delimited path of the account this register shows. */
  account: string;
  /**
   * Row density: `comfortable` (payee and narration stacked, 2 lines/row) or
   * `compact` (single line). Affects both CSS row height and the JS row
   * height used for window math, so it must not change between renders
   * without a full re-render.
   */
  density?: RegisterDensity;
  /**
   * Interleaves period group header rows (month/quarter/year) into the row
   * space. Default `none`, which keeps the flat pure-arithmetic window fast
   * path. Group headers are plain rows in v1 — intentionally NOT sticky.
   */
  groupBy?: RegisterGroupBy;
  /**
   * Stable instance id baked into row `id` attributes (and thus
   * `aria-activedescendant`). Pass the same id to `preloadRegisterHTML` so
   * SSR output and the hydrated client agree — the AccountTree contract.
   * Auto-generated by the client Register when omitted; SSR output carries
   * no row ids when omitted.
   */
  id?: string;
  /**
   * Accessible name for the register grid (`aria-label`). Defaults to the
   * account path — the same string the sticky header already presents
   * visually, so assistive tech and sighted users hear/see the same name.
   */
  label?: string;
  /**
   * Selection behavior (documented on RegisterOptions). Lives on the render
   * options so SSR can emit `aria-multiselectable` in agreement with the
   * client: `range` is the multi-select mode.
   */
  selectionMode?: RegisterSelectionMode;
  /**
   * Opts out of keyboard navigation (documented on RegisterOptions). The
   * renderer mirrors it by dropping the grid's `tabindex="0"` so SSR markup
   * and client behavior agree on whether the register is a tab stop.
   */
  disableKeyboardNavigation?: boolean;
  /**
   * Projection-level row filter (see {@link RegisterFilter}). Lives on the
   * render options so SSR emits the same filtered rows, recomputed group
   * summaries, aria-rowcount, and match highlights the hydrated client
   * would produce — the worker/SSR byte-parity contract extended to
   * filtering. Empty/absent query keeps today's unfiltered output.
   */
  filter?: RegisterFilter;
  /**
   * Caps how many rows the SSR pass emits into the initial HTML. The server
   * cannot know the viewport, so by default it renders every row — fine for
   * ordinary registers, but an unbounded string build for the very large
   * ledgers this library targets (hundreds of thousands of rows). Set this to
   * a value comfortably larger than any first-paint viewport (a few hundred)
   * to bound the SSR payload: the client re-windows on its first virtualized
   * pass regardless, and the hydration `rows` come from JS, not the DOM, so
   * capped output hydrates to the identical result — only the pre-hydration
   * paint shows fewer rows.
   *
   * Ignored when a filter or grouping is active (those models are already
   * bounded by the match/group set and must render in full so hydration
   * adopts the exact structure). Values `<= 0` or absent mean "render all".
   */
  maxSsrRows?: number;
  /**
   * Sticky current-period label for grouped registers. Default ON whenever
   * `groupBy !== 'none'` (new surface, so no back-compat concern): a slim
   * aria-hidden mirror strip pinned just below the register's sticky header
   * shows the period the top visible row belongs to. Mirror-based (the
   * accounts sticky-ancestor pattern) because `position: sticky` cannot work
   * on the real group rows inside a virtualized window — they are evicted
   * and recreated as the window moves. The real group row keeps all grid
   * semantics; the mirror is pure presentation.
   */
  stickyGroupLabels?: boolean;
}

/**
 * Number of gridcell columns in an entry row (date / flag / description /
 * amount / balance). Group header rows span all of them via `aria-colspan`.
 */
export const REGISTER_COLUMN_COUNT = 5;

/**
 * Which entry rows are selected: a single entry index (legacy single-row
 * selection), a set of entry indexes (range selection), or null for none.
 * Always entry-index space — group header rows are never selectable.
 */
export type RegisterSelectedRows = number | ReadonlySet<number> | null;

/**
 * Filter normalized once per rendered window (not per row): the query
 * pre-lowercased for the indexOf highlight walk, plus the resolved field
 * set gating WHICH text cells receive `<mark data-filter-match>` wraps.
 */
export interface PreparedRegisterFilter {
  lowerQuery: string;
  fields: ReadonlySet<RegisterFilterField>;
}

// Normalizes a RegisterFilter for the row renderers; null when the filter is
// absent or its query empty (no filter → zero highlight work per row). The
// default field set must match computeRegisterFilterMatches' default so a
// row can never be kept by a field the renderer refuses to highlight.
export function prepareRegisterFilter(
  filter: RegisterFilter | null | undefined
): PreparedRegisterFilter | null {
  if (filter == null || filter.query === '') {
    return null;
  }
  return {
    lowerQuery: filter.query.toLowerCase(),
    fields: new Set(filter.fields ?? ['description']),
  };
}

// Like EntryRenderer, these are pure string builders shared by the client
// Register component (innerHTML) and the SSR preload path. No DOM APIs.

// Sticky section header: account path plus current balances (one span per
// currency present in the final running balance).
export function renderRegisterHeaderHTML(
  account: string,
  balance: ReadonlyMap<string, MinorUnits> | null
): string {
  let html = '<header data-register-header data-sticky>';
  html += `<span data-account>${renderAccountPathHTML(account)}</span>`;
  html += '<span data-register-balance>';
  if (balance != null) {
    for (const [currency, amount] of balance) {
      const negative = amount < 0 ? ' data-balance-negative="true"' : '';
      html +=
        `<span data-balance-amount${negative}>` +
        `${formatMinorUnits(amount, currency)}` +
        ` <span data-currency>${escapeHtml(currency)}</span></span>`;
    }
  }
  html += '</span></header>';
  return html;
}

// One register row: date / flag dot / payee + narration / signed amount /
// running balance. The row index is baked into a data attribute so event
// delegation can map DOM hits back to data without per-row listeners.
// ARIA grid semantics: `role="row"`, `aria-rowindex` (1-based position in
// the FULL row model — under grouping the caller passes the model index so
// interleaved group headers count), `aria-selected` (always emitted: the
// register always has a selection mode, single by default), and a stable
// `id="{idPrefix}-row-{entryIndex}"` for `aria-activedescendant` when the
// caller supplies an id prefix. `ariaRowIndex` defaults to `index + 1`,
// which is correct exactly on the flat (ungrouped) path. With a prepared
// `filter`, matched substrings in the text cells the filter targets wrap in
// `<mark data-filter-match>` (flag matches have no text cell — the flag
// renders as a dot — so they carry no visible highlight).
export function renderRegisterRowHTML(
  row: RegisterRowData,
  index: number,
  selected: boolean,
  ariaRowIndex: number = index + 1,
  idPrefix?: string,
  filter?: PreparedRegisterFilter | null
): string {
  const { entry, posting } = row;
  const direction = posting.amount < 0 ? 'credit' : 'debit';
  const selectedAttribute = selected ? " data-row-selected='true'" : '';
  const idAttribute =
    idPrefix != null && idPrefix !== ''
      ? ` id="${escapeHtml(idPrefix)}-row-${index}"`
      : '';
  let html =
    `<div data-row data-row-index="${index}" role="row"` +
    ` aria-rowindex="${ariaRowIndex}" aria-selected="${selected}"${idAttribute}` +
    ` data-amount="${direction}"` +
    ` data-flag="${escapeHtml(entry.flag)}"${selectedAttribute}>`;
  const dateHTML =
    filter != null && filter.fields.has('date')
      ? renderFilterHighlightHTML(entry.date, filter.lowerQuery)
      : escapeHtml(entry.date);
  html += `<span data-cell="date" role="gridcell">${dateHTML}</span>`;
  html += `<span data-cell="flag" role="gridcell">${renderFlagDotHTML(entry.flag)}</span>`;
  html += renderDescriptionCellHTML(
    entry.payee,
    entry.narration,
    filter != null && filter.fields.has('description') ? filter : null
  );
  html +=
    `<span data-cell="amount" role="gridcell"><span data-amount-sign="${direction}" aria-hidden="true"></span>` +
    '<span data-amount-value>' +
    `${formatMinorUnits(posting.amount, posting.currency, { sign: 'never' })}` +
    '</span></span>';
  html += renderBalanceCellHTML(row);
  html += '</div>';
  return html;
}

// One period group header row. Indexing decision, documented here where the
// attributes are defined: `data-row-index` always carries the ENTRY index
// (so selection, callbacks, and re-window patching stay coherent under
// grouping), while group rows carry `data-group-row` + `data-group-key` and
// deliberately NO `data-row`/`data-row-index` — the InteractionManager's
// `closest('[data-row]')` therefore never resolves a group row, which makes
// them unselectable and hover-inert for free. Sticky group headers are
// intentionally out of scope for v1 (kept as plain separator rows).
// ARIA: group headers are real grid rows (`role="row"` + `aria-rowindex` in
// model space) whose content lives in ONE full-width gridcell spanning every
// entry column via `aria-colspan` — but they stay non-interactive: no
// tabindex, no id, never a focus or selection target.
export function renderRegisterGroupRowHTML(
  group: RegisterGroupSummary,
  ariaRowIndex?: number
): string {
  const rowIndexAttribute =
    ariaRowIndex != null ? ` aria-rowindex="${ariaRowIndex}"` : '';
  let html =
    `<div data-group-row role="row"${rowIndexAttribute}` +
    ` data-group-key="${escapeHtml(group.key)}">`;
  html += `<span data-group-cell role="gridcell" aria-colspan="${REGISTER_COLUMN_COUNT}">`;
  html += `<span data-group-label>${escapeHtml(group.label)}</span>`;
  html += '<span data-group-meta>';
  html +=
    `<span data-group-count>${group.entryCount}` +
    ` ${group.entryCount === 1 ? 'entry' : 'entries'}</span>`;
  for (const [currency, amount] of group.netChange) {
    const negative = amount < 0 ? ' data-net-negative="true"' : '';
    html +=
      `<span data-group-net${negative}>` +
      `${formatMinorUnits(amount, currency, { sign: 'always' })}` +
      ` <span data-currency>${escapeHtml(currency)}</span></span>`;
  }
  html += '</span></span></div>';
  return html;
}

// The sticky mirror strip's inner row for one period group. Reuses the
// group-row CSS vocabulary (data-group-row and children) so the mirror is
// pixel-identical to the real row it shadows, but deliberately carries NO
// role/aria-rowindex/data-group-key — the real group row in the grid owns
// the semantics; the mirror lives inside an aria-hidden container and is
// pure presentation.
export function renderStickyGroupLabelHTML(
  group: RegisterGroupSummary
): string {
  let html = '<div data-group-row data-sticky-mirror>';
  html += '<span data-group-cell>';
  html += `<span data-group-label>${escapeHtml(group.label)}</span>`;
  html += '<span data-group-meta>';
  html +=
    `<span data-group-count>${group.entryCount}` +
    ` ${group.entryCount === 1 ? 'entry' : 'entries'}</span>`;
  for (const [currency, amount] of group.netChange) {
    const negative = amount < 0 ? ' data-net-negative="true"' : '';
    html +=
      `<span data-group-net${negative}>` +
      `${formatMinorUnits(amount, currency, { sign: 'always' })}` +
      ` <span data-currency>${escapeHtml(currency)}</span></span>`;
  }
  html += '</span></span></div>';
  return html;
}

// Renders the `[start, end)` slice of rows in one string so the component
// can commit a whole window with a single innerHTML write. `selected`
// accepts the legacy single index or a set of entry indexes; both produce
// identical bytes for the same effective selection.
export function renderRegisterRowsHTML(
  rows: readonly RegisterRowData[],
  range: RowRange,
  selected: RegisterSelectedRows,
  idPrefix?: string
): string {
  let html = '';
  for (let index = range.start; index < range.end; index += 1) {
    // Flat register: the entry index IS the model index, so aria-rowindex is
    // simply index + 1 (the renderRegisterRowHTML default).
    html += renderRegisterRowHTML(
      rows[index],
      index,
      isRowIndexSelected(selected, index),
      index + 1,
      idPrefix
    );
  }
  return html;
}

// Grouped-register counterpart of renderRegisterRowsHTML: the `[start, end)`
// slice of the virtual row model (group headers + entry rows) in one string.
// Range indexes are MODEL indexes; entry rows still stamp their original
// entry index into `data-row-index`. When the model was built under a
// filter, pass that same filter so matched substrings get their marks —
// aria-rowindex stays the 1-based position within THIS (possibly filtered)
// model: it describes the presented grid, not the full dataset (the honesty
// rule from the accounts tree's filtered posinset).
export function renderRegisterVirtualRowsHTML(
  model: readonly RegisterVirtualRow[],
  range: RowRange,
  selected: RegisterSelectedRows,
  idPrefix?: string,
  filter?: RegisterFilter | null
): string {
  const prepared = prepareRegisterFilter(filter);
  let html = '';
  for (let index = range.start; index < range.end; index += 1) {
    const item = model[index];
    // aria-rowindex is the 1-based MODEL position (group headers count as
    // grid rows), while data-row-index/id stay in entry space.
    html +=
      item.kind === 'group'
        ? renderRegisterGroupRowHTML(item.group, index + 1)
        : renderRegisterRowHTML(
            item.row,
            item.entryIndex,
            isRowIndexSelected(selected, item.entryIndex),
            index + 1,
            idPrefix,
            prepared
          );
  }
  return html;
}

// Single window renderer shared by the worker, its main-thread fallback, and
// SSR: rebuilds the (grouped and/or filtered) row model deterministically
// from (rows, groupBy, filter) so every path produces byte-identical HTML to
// the client's cached-model sync path. The client Register does NOT call
// this per window — it renders from its precomputed model — but because the
// model builders and the match test are pure, the outputs cannot drift. An
// active filter forces the model path even for groupBy 'none' (the client
// mirrors this: filtered flat registers window over a model too), and the
// range is then in FILTERED-model-index space.
export function renderRegisterWindowHTML(
  rows: readonly RegisterRowData[],
  range: RowRange,
  selected: RegisterSelectedRows,
  groupBy?: RegisterGroupBy,
  idPrefix?: string,
  filter?: RegisterFilter | null
): string {
  const activeFilter = filter != null && filter.query !== '' ? filter : null;
  if (activeFilter != null) {
    return renderRegisterVirtualRowsHTML(
      buildFilteredRegisterRowModel(
        rows,
        groupBy ?? 'none',
        computeRegisterFilterMatches(rows, activeFilter)
      ),
      range,
      selected,
      idPrefix,
      activeFilter
    );
  }
  if (groupBy != null && groupBy !== 'none') {
    return renderRegisterVirtualRowsHTML(
      buildRegisterRowModel(rows, groupBy),
      range,
      selected,
      idPrefix
    );
  }
  return renderRegisterRowsHTML(rows, range, selected, idPrefix);
}

// Full register HTML for SSR: sticky header plus every row with zero-height
// spacers. The server cannot know the viewport, so it renders everything and
// the client Register re-windows on its first virtualized render pass. When
// groupBy is active the grouped row model is rendered in full so hydration
// adopts the exact structure the client would produce.
export function renderRegisterHTML(
  rows: readonly RegisterRowData[],
  options: RegisterRenderOptions
): string {
  const { account, density = 'comfortable', groupBy = 'none' } = options;
  // The header balance stays the FULL register's running balance even under
  // a filter: it names the account's balance, not a sum of visible rows, so
  // filtering must not restate it.
  const balance = rows.length > 0 ? rows[rows.length - 1].runningBalance : null;
  const filter =
    options.filter != null && options.filter.query !== ''
      ? options.filter
      : null;
  // Active filters use the filtered model (matched rows only, recomputed
  // group summaries) even for groupBy 'none' — exactly the client's model
  // selection, so hydration adopts identical structure.
  const model =
    filter != null
      ? buildFilteredRegisterRowModel(
          rows,
          groupBy,
          computeRegisterFilterMatches(rows, filter)
        )
      : groupBy !== 'none'
        ? buildRegisterRowModel(rows, groupBy)
        : null;
  // ARIA grid decisions, documented once where they are emitted:
  // - The <section> is the grid (not the scroller): LedgerView stacks many
  //   registers in ONE shared scroller, and each section must stay its own
  //   grid with its own focus/activedescendant state.
  // - aria-rowcount counts MODEL rows only (entry rows + interleaved group
  //   headers). The sticky register header presents the account path and
  //   running balance — not column names — so no columnheader row is faked
  //   and the header is not counted; it simply lives outside grid row
  //   semantics, like the accounts tree's sticky header.
  // - tabindex="0" makes the grid the single tab stop (focus moves between
  //   rows virtually via aria-activedescendant); dropped when keyboard
  //   navigation is disabled so SSR and client agree on tab order.
  let html =
    `<section data-register data-density="${density}" role="grid"` +
    ` aria-label="${escapeHtml(options.label ?? account)}"` +
    ` aria-rowcount="${model != null ? model.length : rows.length}"`;
  if (options.selectionMode === 'range') {
    html += ' aria-multiselectable="true"';
  }
  if (options.disableKeyboardNavigation !== true) {
    html += ' tabindex="0"';
  }
  html += '>';
  html += renderRegisterHeaderHTML(account, balance);
  // Sticky mirror gates on GROUPING, not on the model existing — a filtered
  // flat register has a model but no group rows to mirror.
  if (groupBy !== 'none' && options.stickyGroupLabels !== false) {
    // Sticky mirror container between header and body: emitted hidden and
    // empty (the pre-scroll state — at scrollTop 0 no group header has
    // scrolled off) so hydration adopts it without a rebuild. The inline
    // `top` pins it below the sticky register header; SSR options carry no
    // headerHeight, so this is the default — clients with a custom
    // headerHeight re-pin it on adoption.
    html += renderStickyGroupContainerHTML(DEFAULT_HEADER_HEIGHT);
  }
  html += '<div data-register-body>';
  html += '<div data-register-spacer="before" style="height: 0px"></div>';
  html += '<div data-register-rows>';
  if (model != null) {
    html += renderRegisterVirtualRowsHTML(
      model,
      { start: 0, end: model.length },
      null,
      options.id,
      filter
    );
  } else {
    // Bound the flat SSR payload when asked. The client owns the real
    // windowing; capping here only trims the initial paint, and since the
    // spacers stay 0px (the client recomputes them on the first pass) the
    // hydrated result is identical whether or not the cap fired.
    const ssrEnd =
      options.maxSsrRows != null && options.maxSsrRows > 0
        ? Math.min(rows.length, options.maxSsrRows)
        : rows.length;
    html += renderRegisterRowsHTML(
      rows,
      { start: 0, end: ssrEnd },
      null,
      options.id
    );
  }
  html += '</div>';
  html += '<div data-register-spacer="after" style="height: 0px"></div>';
  html += '</div></section>';
  return html;
}

// The sticky mirror container shell shared by SSR (renderRegisterHTML) and
// the client (populateSectionElement / adoptSection): a zero-height sticky
// element pinned `headerHeight` below the viewport top — height 0 so it
// occupies no flow space and spacer/window math stays untouched — whose
// overflowing child strip is the visible label. aria-hidden because the
// real group row in the grid carries the semantics.
export function renderStickyGroupContainerHTML(headerHeight: number): string {
  return (
    `<div data-group-sticky aria-hidden="true" hidden` +
    ` style="top: ${headerHeight}px"></div>`
  );
}

// Membership test unifying the two selection representations so single-index
// callers and set-based range selection render identical markup.
function isRowIndexSelected(
  selected: RegisterSelectedRows,
  index: number
): boolean {
  if (selected == null) {
    return false;
  }
  return typeof selected === 'number'
    ? selected === index
    : selected.has(index);
}

// Payee is the primary description line when present; narration becomes the
// secondary line. Payee-less entries promote narration to primary so compact
// rows never render an empty first line. A prepared filter (already gated on
// the 'description' field by the caller) highlights matches within each line
// independently — matching also treats payee and narration as separate lines
// (the '\n'-joined corpus), so highlight and match agree by construction.
function renderDescriptionCellHTML(
  payee: string | null,
  narration: string,
  filter: PreparedRegisterFilter | null = null
): string {
  const renderText = (text: string): string =>
    filter != null
      ? renderFilterHighlightHTML(text, filter.lowerQuery)
      : escapeHtml(text);
  let html = '<span data-cell="description" role="gridcell">';
  if (payee != null && payee !== '') {
    html += `<span data-payee>${renderText(payee)}</span>`;
    if (narration !== '') {
      html += `<span data-narration>${renderText(narration)}</span>`;
    }
  } else if (narration !== '') {
    html += `<span data-payee>${renderText(narration)}</span>`;
  }
  html += '</span>';
  return html;
}

// Running balance in the posting's own currency. A missing currency in the
// running-balance map is bad input; render an empty cell rather than a made
// up number (graceful degradation, never silent repair).
function renderBalanceCellHTML(row: RegisterRowData): string {
  const balance = row.runningBalance.get(row.posting.currency);
  if (balance == null) {
    return '<span data-cell="balance" role="gridcell"></span>';
  }
  const negative = balance < 0 ? ' data-balance-negative="true"' : '';
  return (
    `<span data-cell="balance" role="gridcell"${negative}>` +
    `<span data-balance-value>${formatMinorUnits(balance, row.posting.currency)}</span>` +
    ` <span data-currency>${escapeHtml(row.posting.currency)}</span></span>`
  );
}
