// Handcrafted chart of accounts for a Malaysian SME (Sdn Bhd trading /
// services company). Realistic enough to exercise every tree shape the
// account store must handle: deep nesting (4 levels), wide sibling groups,
// statutory payroll liabilities (EPF/SOCSO/EIS/PCB/HRDF), SST, and
// multi-bank cash. Paths are canonical colon-delimited leaf accounts;
// group nodes (`Assets:Current`) are implied by their descendants.

/** ~150 leaf account paths for a Malaysian SME. */
export const CHART_OF_ACCOUNTS: readonly string[] = [
  // --- Assets: cash and banks -----------------------------------------------
  'Assets:Current:Cash-Maybank',
  'Assets:Current:Cash-CIMB',
  'Assets:Current:Cash-PublicBank',
  'Assets:Current:Cash-Wise',
  'Assets:Current:Cash-PettyCash',
  'Assets:Current:Cash-TnG-eWallet',
  // --- Assets: receivables and other current --------------------------------
  'Assets:Current:AR',
  'Assets:Current:AR-Related-Parties',
  'Assets:Current:Deposits-Suppliers',
  'Assets:Current:Prepayments-Insurance',
  'Assets:Current:Prepayments-Rent',
  'Assets:Current:Prepayments-Software',
  'Assets:Current:Staff-Advances',
  'Assets:Current:Tax-Refundable',
  'Assets:Current:Inventory:Raw-Materials',
  'Assets:Current:Inventory:Work-In-Progress',
  'Assets:Current:Inventory:Finished-Goods',
  'Assets:Current:Inventory:Goods-In-Transit',
  // --- Assets: non-current ----------------------------------------------------
  'Assets:NonCurrent:PPE:Computers',
  'Assets:NonCurrent:PPE:Office-Equipment',
  'Assets:NonCurrent:PPE:Furniture-Fittings',
  'Assets:NonCurrent:PPE:Motor-Vehicles',
  'Assets:NonCurrent:PPE:Renovation',
  'Assets:NonCurrent:PPE:Plant-Machinery',
  'Assets:NonCurrent:AccumDepr:Computers',
  'Assets:NonCurrent:AccumDepr:Office-Equipment',
  'Assets:NonCurrent:AccumDepr:Furniture-Fittings',
  'Assets:NonCurrent:AccumDepr:Motor-Vehicles',
  'Assets:NonCurrent:AccumDepr:Renovation',
  'Assets:NonCurrent:AccumDepr:Plant-Machinery',
  'Assets:NonCurrent:Investments:Fixed-Deposit-Maybank',
  'Assets:NonCurrent:Investments:ASB',
  'Assets:NonCurrent:Deposits:Office-Rental',
  'Assets:NonCurrent:Deposits:Utilities',
  'Assets:NonCurrent:Intangibles:Software-Licenses',
  'Assets:NonCurrent:Intangibles:Trademarks',
  // --- Liabilities: current ----------------------------------------------------
  'Liabilities:Current:AP',
  'Liabilities:Current:AP-Related-Parties',
  'Liabilities:Current:Accruals-Audit-Fee',
  'Liabilities:Current:Accruals-Bonus',
  'Liabilities:Current:Accruals-Utilities',
  'Liabilities:Current:SST-Payable',
  'Liabilities:Current:EPF-Payable',
  'Liabilities:Current:SOCSO-Payable',
  'Liabilities:Current:EIS-Payable',
  'Liabilities:Current:PCB-Payable',
  'Liabilities:Current:HRDF-Payable',
  'Liabilities:Current:Zakat-Payable',
  'Liabilities:Current:CP204-Tax-Instalment',
  'Liabilities:Current:CreditCard-Maybank',
  'Liabilities:Current:CreditCard-CIMB',
  'Liabilities:Current:Directors-Loan',
  'Liabilities:Current:Deferred-Revenue',
  'Liabilities:Current:Customer-Deposits',
  // --- Liabilities: non-current -------------------------------------------------
  'Liabilities:NonCurrent:TermLoan-Maybank',
  'Liabilities:NonCurrent:TermLoan-SME-Bank',
  'Liabilities:NonCurrent:HirePurchase-Motor-Vehicles',
  'Liabilities:NonCurrent:Deferred-Tax',
  // --- Equity ---------------------------------------------------------------------
  'Equity:Share-Capital',
  'Equity:Retained-Earnings',
  'Equity:Current-Year-Earnings',
  'Equity:Dividends-Paid',
  // --- Income ---------------------------------------------------------------------
  'Income:Sales:Products-Domestic',
  'Income:Sales:Products-Export',
  'Income:Sales:Services-Consulting',
  'Income:Sales:Services-Maintenance',
  'Income:Sales:Shopee',
  'Income:Sales:Lazada',
  'Income:Sales:TikTok-Shop',
  'Income:Sales:Marketplace-Commissions',
  'Income:Other:Interest-Fixed-Deposit',
  'Income:Other:Forex-Gain',
  'Income:Other:Government-Grants',
  'Income:Other:Rental-Income',
  'Income:Other:Rebates',
  'Income:Other:Scrap-Sales',
  // --- Expenses: cost of goods sold -------------------------------------------------
  'Expenses:COGS:Materials',
  'Expenses:COGS:Freight-Inward',
  'Expenses:COGS:Customs-Duty',
  'Expenses:COGS:Packaging',
  'Expenses:COGS:Subcontractors',
  'Expenses:COGS:Inventory-Writeoff',
  // --- Expenses: payroll --------------------------------------------------------------
  'Expenses:Payroll:Salaries',
  'Expenses:Payroll:Directors-Remuneration',
  'Expenses:Payroll:Bonus',
  'Expenses:Payroll:Overtime',
  'Expenses:Payroll:Allowances',
  'Expenses:Payroll:Commission',
  'Expenses:Payroll:EPF',
  'Expenses:Payroll:SOCSO',
  'Expenses:Payroll:EIS',
  'Expenses:Payroll:HRDF',
  'Expenses:Payroll:Staff-Welfare',
  'Expenses:Payroll:Staff-Training',
  'Expenses:Payroll:Medical',
  'Expenses:Payroll:Recruitment',
  // --- Expenses: premises ----------------------------------------------------------------
  'Expenses:Rent:Office',
  'Expenses:Rent:Warehouse',
  'Expenses:Rent:Equipment',
  'Expenses:Utilities:Electricity-TNB',
  'Expenses:Utilities:Water-Air-Selangor',
  'Expenses:Utilities:Internet-TM-Unifi',
  'Expenses:Utilities:Mobile-Maxis',
  'Expenses:Utilities:Sewerage-IWK',
  // --- Expenses: professional fees ----------------------------------------------------------
  'Expenses:Professional:Audit-Fee',
  'Expenses:Professional:Tax-Agent-Fee',
  'Expenses:Professional:Secretarial-Fee',
  'Expenses:Professional:Legal-Fee',
  'Expenses:Professional:Consulting',
  'Expenses:Professional:Valuation-Fee',
  // --- Expenses: marketing ---------------------------------------------------------------------
  'Expenses:Marketing:Ads-Google',
  'Expenses:Marketing:Ads-Meta',
  'Expenses:Marketing:Ads-TikTok',
  'Expenses:Marketing:Events-Exhibitions',
  'Expenses:Marketing:Printing-Signage',
  'Expenses:Marketing:Sponsorship',
  'Expenses:Marketing:Website',
  // --- Expenses: software and subscriptions ------------------------------------------------------
  'Expenses:Software:AWS',
  'Expenses:Software:Google-Workspace',
  'Expenses:Software:Microsoft-365',
  'Expenses:Software:Accounting-SaaS',
  'Expenses:Software:CRM-SaaS',
  'Expenses:Software:Design-Tools',
  // --- Expenses: travel ----------------------------------------------------------------------------
  'Expenses:Travel:Flights',
  'Expenses:Travel:Hotels',
  'Expenses:Travel:Grab',
  'Expenses:Travel:Mileage-Claims',
  'Expenses:Travel:Parking-Tolls',
  'Expenses:Travel:Meals-Entertainment',
  // --- Expenses: office and admin --------------------------------------------------------------------
  'Expenses:Office:Stationery',
  'Expenses:Office:Postage-Courier',
  'Expenses:Office:Cleaning',
  'Expenses:Office:Repairs-Maintenance',
  'Expenses:Office:Pantry',
  'Expenses:Office:Security',
  'Expenses:Office:Small-Equipment',
  // --- Expenses: vehicles ------------------------------------------------------------------------------
  'Expenses:Vehicle:Fuel',
  'Expenses:Vehicle:Maintenance',
  'Expenses:Vehicle:Insurance-RoadTax',
  'Expenses:Vehicle:Parking',
  // --- Expenses: financial and statutory ----------------------------------------------------------------
  'Expenses:Insurance:General-Business',
  'Expenses:Insurance:Professional-Indemnity',
  'Expenses:Insurance:Group-Hospitalization',
  'Expenses:Bank:Charges',
  'Expenses:Bank:Interest-TermLoan',
  'Expenses:Bank:Interest-HirePurchase',
  'Expenses:Bank:Merchant-Fees',
  'Expenses:Forex:Loss',
  'Expenses:Depreciation:Computers',
  'Expenses:Depreciation:Office-Equipment',
  'Expenses:Depreciation:Furniture-Fittings',
  'Expenses:Depreciation:Motor-Vehicles',
  'Expenses:Depreciation:Renovation',
  'Expenses:Depreciation:Plant-Machinery',
  'Expenses:Statutory:Business-Licenses',
  'Expenses:Statutory:SSM-Filing',
  'Expenses:Statutory:Stamp-Duty',
  'Expenses:Statutory:Penalties',
  'Expenses:Tax:Income-Tax',
  'Expenses:Tax:Zakat',
];
